
spring:
  application:
    name: data-refill-center-coupon
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/data_refill_center_coupon?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: root

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 9002